### ISSUE TITLE
Fix Session Persistence for User Authentication (BUG)

### ISSUE THREAD

**Issue by AlbinXXX** [AlbinXXX/FlowForms#116]
Ensure user sessions are persistent, even after the server restarts.

**Comment by AlbinXXX** [comment]
@AnujChhikara, I'd really appreciate it if you could take a look at this, as I’m onboarding a few other members.

**Comment by AnujChhikara** [comment]
yeah sure

**Comment by AlbinXXX** [comment]
perfect
